language: go
sudo: required

matrix:
  allow_failures:
    - go: master
  include:
    # Supported versions of Go: https://golang.org/dl/
    - go: "1.13.x"
    - go: "1.14.x"
    - go: master

go_import_path: github.com/rucciva/goycql-migrate

env:
  global:
    - GO111MODULE=on

services:
    - docker

cache:
  directories:
    - $GOPATH/pkg

before_install:
  # Update docker to latest version: https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - go test